[package]
authors = ["Lee Bousfield <ljbousfield@gmail.com>"]
name = "random-walk"
version = "0.1.0"

[dependencies]
clap = { version = "2", features = ["yaml"] }
rand = "0.3"
lazy_static = "0.2"
fnv = "1"
